# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- final_state

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'TestProject.sln'
    arguments: '--filter Category=Automations'
    
- task: SpecFlowPlus@0
  inputs:
    generatorSource: 'FeatureFolder'
    projectFilePath: 'TestProject'
    projectName: 'BddAndSpecFlow.csproj'
    testExecutionJson: 'TestProject/**/TestExecution.json'
    